language: python
services: docker
python:
  - "3.6"
before_install:
  - docker build ./docker/web_server/
install:
  - docker-compose up -d
  - pip install -r requirements.txt
  - sleep 15
script:
  - sudo pytest
