language: python
services: docker
python:
  - "3.6"
env:
  - DOCKER_COMPOSE_VERSION=3
before_install:
   - chmod +x docker-compose
  - docker build ./docker/web_server/
install:
  - docker-compose up -d
  - pip install -r requirements.txt
  - sleep 300
script:
  - pytest
