DROP DATABASE IF EXISTS metube;
CREATE DATABASE metube;
USE metube;

DROP TABLE IF EXISTS user;
CREATE TABLE user(
	userID INT UNSIGNED  NOT NULL AUTO_INCREMENT,
	username VARCHAR(30) NOT NULL,
	password VARCHAR(30) NOT NULL
);

SHOW TABLES;
DESCRIBE user;

